### ISSUE TITLE
Yamlinclude moved to a new major version

### ISSUE THREAD

**Issue by Helw150** [dlwh/draccus#12]
![image](https://github.com/dlwh/draccus/assets/9847335/f7ac5179-6499-4c85-8b06-79ccd46585d4)

This causes import errors when loading Draccus and in downstream libraries (e.g. Levanter).

**Comment by matthiasbuchner** [comment]
I worked around this issue by running:
`pip install pyyaml-include==1.4.1`

then using the `-U` option for the following pip installs:
`pip install -U .`
